;
; Maps each realtime family to the pgsql engine + table (schema created by
; Asterisk's official Alembic migrations, see docker/migrate).
;
[settings]
ps_endpoints => pgsql,asterisk,ps_endpoints
ps_auths => pgsql,asterisk,ps_auths
ps_aors => pgsql,asterisk,ps_aors
ps_domain_aliases => pgsql,asterisk,ps_domain_aliases
ps_endpoint_id_ips => pgsql,asterisk,ps_endpoint_id_ips
ps_contacts => pgsql,asterisk,ps_contacts
