;
; Confirmed live as a real gap: this image shipped no musiconhold.conf at all, so
; `moh show classes` returned nothing and /var/lib/asterisk/moh/ was empty — every "on hold"
; bridge (queues created via ICallCenterProvider.CreateQueueAsync, §5's MOH fix, and any
; holding bridge Dograh's own ARI app might use) had a MOH engine with literally nothing to
; play. asterisk-moh-opsound-wav (installed in the Dockerfile) is the real Debian package
; Asterisk's own default installer uses for out-of-the-box MOH — royalty-free Opsound-licensed
; tracks, not placeholder/synthetic audio.
[default]
mode = files
directory = /usr/share/asterisk/moh
random = yes
