// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ringly.Samples.WebApi.Brokers.Storages;

#nullable disable

namespace Ringly.Samples.WebApi.Migrations
{
    [DbContext(typeof(StorageBroker))]
    partial class StorageBrokerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ringly.Samples.WebApi.Models.Foundations.TelephonyCalls.TelephonyCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AsteriskBridgeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AsteriskChannelId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("CallerIdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecipientIdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CallerIdentityId");

                    b.HasIndex("RecipientIdentityId");

                    b.ToTable("TelephonyCalls");
                });

            modelBuilder.Entity("Ringly.Samples.WebApi.Models.Foundations.TelephonyDevices.TelephonyDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastRegisteredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastUnregisteredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("TelephonyDevices");
                });

            modelBuilder.Entity("Ringly.Samples.WebApi.Models.Foundations.TelephonyIdentities.TelephonyIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SipCredential")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SipUsername")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type")
                        .IsUnique();

                    b.ToTable("TelephonyIdentities");
                });

            modelBuilder.Entity("Ringly.Samples.WebApi.Models.Foundations.TelephonyCalls.TelephonyCall", b =>
                {
                    b.HasOne("Ringly.Samples.WebApi.Models.Foundations.TelephonyIdentities.TelephonyIdentity", null)
                        .WithMany()
                        .HasForeignKey("CallerIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ringly.Samples.WebApi.Models.Foundations.TelephonyIdentities.TelephonyIdentity", null)
                        .WithMany()
                        .HasForeignKey("RecipientIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ringly.Samples.WebApi.Models.Foundations.TelephonyDevices.TelephonyDevice", b =>
                {
                    b.HasOne("Ringly.Samples.WebApi.Models.Foundations.TelephonyIdentities.TelephonyIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
